#!/usr/bin/env bash
# Creating HDFS Directory
hdfs dfs -mkdir pre-processing
hdfs dfs -mkdir aggregates
hdfs dfs -mkdir index
hdfs dfs -mkdir mergetree
hdfs dfs -mkdir relationships
hdfs dfs -mkdir relationships-ids
hdfs dfs -mkdir correlations
hdfs dfs -mkdir data
# Load 'datasets' file
hdfs dfs -put datasets.txt data/datasets
